package com.example.social_network.Payload.Util;

public class PathResources {
    public static final String Post ="/post";
    public static final String GetlistPost ="/GetlistPost";
    public static final String POST_MEDIA ="/post-media";
    public static final String UPLOAD ="/upload";
    public static final String INSERT ="/insert";
    public static final String SHARE ="/share";
    public static final String GetUser ="/getuser";
    public static final String SYNC_KEYCLOAK ="/sync-keycloak";
    public static final String KAFKA_DEMO ="/kafka-demo"; // demo Bước 3: test Kafka thông
    public static final String MESSAGE ="/message";
    public static final String CONVERSATION ="/conversation";   // tạo/mở hội thoại
    public static final String CONVERSATIONS ="/conversations";  // danh sách hội thoại (Inbox)
    public static final String SEND ="/send";                    // gửi tin nhắn
    public static final String HISTORY ="/history";              // lịch sử tin nhắn
    public static final String DELETE ="/delete";
    public static final String LIKE ="/like";
    public static final String LIKEPOST ="/likepost";
    public static final String REACT ="/react";
    public static final String UNLIKE ="/unlike";
    public static final String MY_REACTION ="/my-reaction";
    public static final String UPDATE ="/update";
    public static final String POSTLIKE ="/postlike";
    public static final String COMMENT ="/comment";
    public static final String UpdaloadImg ="/updaloadimg";
    public static final String CREATECOMMENT ="/createcomment";
    public static final String GETCOMMENT ="/getcomment";
    public static final String LIST ="/list";
    public static final String REPLIES ="/replies";
    public static final String UPDATECOMMENT ="/updatecomment";
    public static final String DELETECOMMENT ="/deletecomment";
    public static final String LIKECOMMENT ="/likecomment";
    public static final String GETPOSTLIKE ="/getpostlike";
    public static final String FRIENTDSHIP ="/friendship";
    public static final String SENDFRIENDREQUEST ="/sendfriendrequest";
    public static final String ACCEPFRIENDREQUEST ="/accepfriendrequest";
    public static final String BLOCKUSER ="/blockuser";
    public static final String FLOWUSER ="/followuser";
    public static final String UNFRIEND ="/unfriend";
    public static final String REJECTFRIENDREQUEST ="/rejectfriendrequest";
    public static final String FRIENDS ="/friends";
    public static final String FRIENDREQUESTS ="/requests";
    public static final String SENTREQUESTS ="/sent";
    public static final String FRIENDSUGGESTIONS ="/suggestions";
    public static final String UNBLOCKUSER ="/unblock";
    public static final String BLOCKEDLIST ="/blocked";
    public static final String STORY ="/story";
    public static final String STORY_VIEW ="/story-view";
    public static final String HIGHLIGHT ="/highlight";
    public static final String HIGHLIGHTS ="/highlights";
    public static final String SEEN ="/seen";
    public static final String BOOKMARK ="/bookmark";
    public static final String TOGGLE ="/toggle";
    public static final String IDS ="/ids";
    public static final String HASHTAG ="/hashtag";
    public static final String POST_HASHTAG ="/post-hashtag";
    public static final String POST_USER_TAG ="/post-user-tag";
    public static final String TAGGED ="/tagged";
    public static final String SHARERS ="/sharers";
    public static final String Auth ="/auth";
    public static final String REGISTER ="/register";
    public static final String LOGIN ="/login";
    public static final String LOGOUT ="/logout";
    public static final String UpdateUser ="/updateuser";
    public static final String NOTIFICATION ="/notification";
    public static final String UNREAD_COUNT ="/unread-count";
    public static final String READ ="/read";
    public static final String READ_ALL ="/read-all";
}
